### PR TITLE
[BUG] Fix mapping key issue in AnimatePresence component

### LINKED ISSUE #128: [BUG] Mapping key has multiple children
**Describe the bug**

Image

It seems like you're encountering a warning related to React, specifically about non-unique keys within components. In React, when rendering a list of elements, each element should have a unique "key" prop assigned to it. This allows React to efficiently update and manage the list.

The warning you're seeing indicates that you have two children within a component that share the same key, which can lead to unexpected behavior such as duplicated or omitted elements.

To resolve this warning, ensure that each child element within the component has a unique key prop assigned to it. You can use unique identifiers such as database IDs or index values if no other unique identifier is available. This ensures React can properly reconcile and update the list elements.

potential fix: 

```jsx
function MyComponent({ items }) {
  return (
    <ul>
      {items.map((item, index) => (
        <li key={item.id}>{item.name}</li>
      ))}
    </ul>
  );
}
```

In this example, assuming each item in the items array has a unique id, we're using item.id as the key prop to ensure uniqueness. Make sure to replace item.id with the actual unique identifier in your code.

**To Reproduce**
1. Go to 'Dashboard'
2. Open devtools
3. Refresh

> [!IMPORTANT]
> Error is comming from AnimateProsence from framer-motion, due to the children it is wrapping, solution is to map its children.

**Solution**

```jsx
    <AnimatePresence>
          {React.Children.map(children, (child, index) => (
            <m.div key={index}>{child}</m.div>
          ))}
        </AnimatePresence>
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ballyalley-o**
This pull request fixes the mapping key issue in the AnimatePresence component. The issue was causing a warning related to non-unique keys within components. To resolve this, the children of the AnimatePresence component are now mapped with a unique key using the index value. This ensures that each child element has a unique key prop assigned to it.

Fixes #128

### CODE REVIEW

File: src/hook/use-snack/use-snack.tsx [hunk 1]
```diff
@@ -47,7 +46,11 @@ export default function SnackProvider({ children }: SnackProviderProps) {
             <Icon icon={closeSrc} />
           </IconButton>
         )}>
-        <AnimatePresence>{children}</AnimatePresence>
+        <AnimatePresence>
+          {React.Children.map(children, (child, index) => (
```
Comment (in-a-iii) [inline src/hook/use-snack/use-snack.tsx:50]: destructure Children from react instead

Comment (ballyalley-o) [reply src/hook/use-snack/use-snack.tsx:50]: right, will do

**Review by in-a-iii — APPROVED** [review]
great.
